### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by hatimox** [adenvt/laravel-coreui-vue#2]
hello , i just installed your repo and when i run it and open any page i get this error and the page still blank

Uncaught Error: Cannot find module "\resources\sass\*" at webpackMissingModule (app.js:13882)

any idea how to fix this ?
thanks

**Comment by adenvt** [comment]
Try remove folder `node_modules`, then run `npm install` again. Make sure installation done without error and then compile again using `npm run prod`.

If still get error, please complete the following information:
 - OS: [e.g. Ubuntu 16.04, Win 7]
 - Browser: [e.g. chrome, safari]
 - Node Version: [e.g 6.1]
 - PHP Version: [e.g 7.0 7.1]
 - Screenshot of errors
