### ISSUE TITLE
Packages haves vulnerabilities

### ISSUE THREAD

**Issue by Atiladanvi** [adenvt/laravel-coreui-vue#30]
Message after npm install: 
added 1541 packages from 749 contributors and audited 22057 packages in 31.984s
found 11 vulnerabilities (5 moderate, 6 high)

**Comment by adenvt** [comment]
Please not create issue about packages vulnerabilities. Don't worry, Github give me alert if there any vulnerabilities on current **package-lock.json** (which used in production with `npm ci` command), and I will tried to fix them as soon as possible.

I also use Greenkeeper bot to keep package in this repo up to date.

But if you in development, you can simply fix them with `npm audit fix`

**Comment by Atiladanvi** [comment]
i am sorry ! . I will follow you recommendation.
